### ISSUE TITLE
Plugin is blocking Firefox's new multiprocess support

### ISSUE THREAD

**Issue by danielquinn** [chengsun/moz-spdy-indicator#25] opened 2017-06-15 09:38 UTC
Firefox 54 supports window multiprocessing and the speed improvement is substantial. However, plugins like this one that only support the legacy format (ie not webextensions) appear to block this feature.

Given that Firefox 57 is slated to drop all support for legacy formats, this is probably something worth looking into.

**Comment by robsonsobral** [comment] 2017-06-15 12:17
Duplicate of #21 ?

**Comment by danielquinn** [comment] 2017-06-15 12:20
Possibly.  I'm not familiar enough with Firefox's internals to know what e10s is though.

**Comment by chengsun** [comment] 2017-06-15 12:42
Duplicate of #21

**Closed by chengsun** 2017-06-15 12:42 UTC
